
language: node_js

env:
     - DB=postgresql://postgres@localhost:5432/shoe_test
     
node_js:  
   - "8.9.4"
        
before_script:
  - psql -c 'create database shoe_test;' -U postgres
  - psql -U postgres -d shoe_test -a -f shoe_api.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2



